title: <p align="center"> Peh Jia Yuan </p>

logo: "/images/picture.png?raw=true"

description:

  <p align="left">
  Accountancy with Digitalisation and Data Analytics | NTU Final Year Undergraduate seeking Data Analytics opportunities  
  <br><br>

  <p>About me: <strong>This text is bold</strong></p>
  As someone who is driven and team-oriented, I am proactively expanding my skill sets through self-directed learning of various programming languages. My goal is to apply my data analytical skills to improve corporate performance and contribute effectively as a data analyst.
  <br><br>
  </p>


  
theme: jekyll-theme-minimal

